
using System;

public enum E_ModelType
{
    None = 0,
    AP_Octeo = 1,
    AP_Sveltea = 2,
    AP_SvelteaManual = 3,
    AP_Coverly = 4,
    AP_Bellasun = 5,
    AP_Rousillon = 6,
    AP_LeBancSmallFoot = 7,
    AP_LeBancBigFoot = 8,
    AP_LeBancTopCladding = 9,
    AP_LeBancSidesCladding = 10,
    AP_LamasPolicarbonate = 11,
    AP_LamasPVC = 12,
    BAC_SlattedRollfix = 14,
    BAC_IsolaRollfix = 15,
    BAC_Whirloop = 16,
    BAC_Isola = 17,
    BAC_FabricCover_Novatrend = 18,
    BAC_FabricCover_Multiversal = 19,
    BAC_FabricCover_SwissTop = 20,
    BAC_LamasDuotherm = 21,
    BAC_LamasTwist = 22,
    BAC_RollmaticPVC = 23,
    BAC_RollmaticPolycarbonate = 24,
    BAC_RollmaticPolycarbonatePro = 25,
    BAC_SlattedRonda = 26,
    BAC_SlattedLido = 27,
    BAC_SlattedAcoe = 28,
    BAC_SlattedDavos = 29,
    BAC_CladdingAcoe = 30,
    BAC_CladdingQuadro = 31,
    BAC_CladdingLido = 32,
    BAC_CladdingDavos = 33,
    BAC_IsolaAcoe = 34,
    BAC_IsolaRonda = 35,
    BAC_IsolaRondalino = 36,

}
